### ISSUE TITLE
Knxgate doesn't send commands to bus

### ISSUE THREAD

**Issue by ornellino** [papergion/scsknxgate_6#1]
Hi Guido,
     I successfully installed knx firmware 6.009 and pic imange KNX 85.608, I can see status of devices in Home assistant (also in a mqtt explorer) but if I try to open a cover or turn on a switch in HA, it publishes on mqtt but KNXgate doesn't send the telegram on bus (I checked in View Pro bus monitor).
Where I am wrong?
Thankyou 
Andrea

**Comment by papergion** [comment]
Hi

I’m not sure to understand.

Please confirm: knxgate correctly read the devices status on bus: so if you switch on/off a light the status in home assistant is correctly exposed. Only bus-write don’t occurs.

Right?

What type of wifi has your card? (esp8266 or esp8285) ? 

Guido

**Comment by ornellino** [comment]
Yes, I confirm.
I have ESP8266, I attach the /status page.
![image](https://user-images.githubusercontent.com/48414020/149776916-0f60fecf-e66e-4f16-b632-e0489364ee36.png)

Tanks
Andrea

**Comment by papergion** [comment]
You have a wrong PIC firmware version.

V 85.608 work on cards mounting esp8285. You need version 66.xxx

From my repository:  <https://github.com/papergion/scsknxgate_6/tree/master/picimages> scsknxgate_6/picimages at master · papergion/scsknxgate_6 (github.com)  get pic firmware from PICKNX_66.608 and update.

Guido

**Comment by ornellino** [comment]
Done! Now It works perfectly!!

Tankyou Guido!
